services:
  wsrn-lastfm-scrobble:
    image: registry.sccs.swarthmore.edu/sccs/wsrn-lastfm-scrobble/wsrn-lastfm-scrobble:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.wsrn-lastfm-scrobble.entrypoints=https"
        - "traefik.http.routers.wsrn-lastfm-scrobble.rule=((Host(`admin.wsrnfm.com`) || Host(`www.admin.wsrnfm.com`)) && PathPrefix(`/scrobble/`))"
        - "traefik.http.routers.wsrn-lastfm-scrobble.tls=true"
        - "traefik.http.routers.wsrn-lastfm-scrobble.tls.certresolver=letsEncrypt"
        - "traefik.http.services.wsrn-lastfm-scrobble.loadbalancer.server.port=5555"
    networks:
      - traefik

# (re)define traefik proxy network
networks:
  traefik:
    # defined elsewhere
    external: true
